### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by ghost** [JrRadiant/RandPlayNX#1]
add a file called .gitignore at root with following content:

> build/*
> *.elf
> *.nro
> *.pfs0
> *.nso
> *.nacp
> *.nsp
> *.npdm

This will avoid problems with build for users

Thanks for using my keyboard header :)

**Comment by JrRadiant** [comment]
Done; thank you very much for the keyboard implementation!..

**Comment by ghost** [comment]
Thanks but the gitignore you added is useless

**Comment by JrRadiant** [comment]
Oh, sorry, thanks again. (:
